### PR TITLE
Fix potential NPE

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

**Comment by markfisher** [comment]
this doesn't actually address the fact that a user not calling `setup()` would get the NPE

**Comment by ericbottard** [comment]
doh!

Forgot to move that part.

**Comment by ericbottard** [comment]
re-pushed

**Comment by markfisher** [comment]
I'm planning to merge this along with this commit:
https://github.com/markfisher/spring-cloud-deployer/commit/e36499218779237fd3a211f51547cf3055edee99

Please let me know what you think @ericbottard.

**Comment by ericbottard** [comment]
Seems legit. Even less API (removed default constructor) to maintain for us.

**Comment by markfisher** [comment]
cool... merging

**Pull request merged**
