### PR TITLE
add MavenProperties to MavenResource

### PR DESCRIPTION
**Pull request by markfisher**

### CODE REVIEW

**Comment by markfisher** [comment]
This is an alternative to #8 (but we should commit the `exists()` part of that PR regardless)

cc @jvalkeal

**Comment by jvalkeal** [comment]
We can do that `exists()` thing with other PR.

This mostly looks OK, but you should probably copy over those tests(concept what tests do) verifying that remote maven repository settings actually works. If I delete `time` and `log` modules from my local m2 cache, this build actually fails(for same reason why CI build fails).

**Comment by markfisher** [comment]
I will copy over the tests and `exists()` from your PR and update this one.

**Comment by markfisher** [comment]
@jvalkeal I added `exists()` and several of your tests (with some changes)... let me know what you think

**Comment by jvalkeal** [comment]
Looks good to me, lets see if CI barks.

**Pull request merged**
