### PR TITLE
Add URI validation for URIRegistryPopulator

### LINKED ISSUE #176: UriRegistryPopulator should not ignore exception for invalid app names
The UriRegistryPopulator should not ignore IllegalArgumentException [1] when populating the registry from a properties file. This can lead to invalid data getting registered causing problems for users of the app registry.

[1] https://github.com/spring-cloud/spring-cloud-deployer/blob/2c2a0d18cf7271d349a2517aed53ea4f7834edb2/spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulator.java#L85

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- logs error messages where there are URI validation errors
 - Add test

Resolves #176

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Will update the PR based on the discussion in #176 on handling `IllegalArgumentExçeption` and updating JavaDoc.

**Comment by trisberg** [comment]
Do we need this validation? We do this same validation in the implementation for the RdbmsUriRegistry now. I think it is better to leave extra validation to implementations.

**Comment by ilayaperumalg** [comment]
I was thinking we can have the common validation at the top level as the implementations may/may not have the validation.

**Comment by trisberg** [comment]
Merged as commit 1abf9a43bd15c2d5a8f8db10d91526c07033b697

Fixed the warning message formatting and added test for empty URI

**Pull request closed without merging**
