### PR TITLE
Upgrade to Spring Cloud Camden

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/114

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by trisberg** [comment]
Shouldn't we have made this change for 1.1.0.BUILD-SNAPSHOT? We are still on a 1.0.4.BUILD-SNAPSHOT version. That's what we have done for SCDF, 1.0.x uses Brixton while 1.1.x uses Camden.

**Comment by ericbottard** [comment]
Ah, good point. Now, corollary question: should we move to 1.1.0.BUILD-SNAPSHOT? :)

**Comment by trisberg** [comment]
I would say we should, after we create a 1.0.x branch on the commit preceding this change - relates to #119

**Comment by trisberg** [comment]
Why, any later changes including https://github.com/spring-cloud/spring-cloud-deployer/commit/b2e0a2eb8736fdbd6b07b67fee1b977aaef53093 would be a fit for 1.0.x, especially the Brixton upgrade

**Comment by ericbottard** [comment]
Ah, correct. Did not realize there were so few commits after latest release and they were appropriate

**Comment by ericbottard** [comment]
I'm on it. Will push a branch, create a new CI plan and update master to be 1.1.0.B-S

**Comment by trisberg** [comment]
We should also update the parent (spring-cloud-build) to use the latest 1.2.x to match Camden

**Pull request merged**
